### PR TITLE
Update callback.py

### PR DESCRIPTION
**Pull request by igorbb**
Changed line of  -- from keras import backend as K -- to avoid indentation error.

### CODE REVIEW

**Comment by igorbb** [comment]
Pull request is solution to issue : #12

**Comment by jakebian** [comment]
Did you verify that this fixes your issue in your environment? It's a bit of a bizarre bug and to me signals something's wrong with your setup.

It looks like we can remove that import altogether as we're not actually using it - we should do that instead.

**Review by jakebian — CHANGES_REQUESTED** [review]
- [ ] Remove this import altogether

**Comment by igorbb** [comment]
> Did you verify that this fixes your issue in your environment? It's a bit of a bizarre bug and to me signals something's wrong with your setup.

Yes . With This modification it works well.

I also tough the error was weird. But its a clean docker setup for running Keras.

> It looks like we can remove that import altogether as we're not actually using it - we should do that instead.

Indeed. I did not read the code with a 100 of attention, and never realized that the backend is not being used.

**Pull request closed without merging**
